[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mixer"
version = "0.1.0"
description = "Python toolkit for parsing, editing, merging, and assembling Martini 3 coarse-grained topologies"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Luís Borges Araújo", email = "luis.borges@ens-lyon.fr"},
  { name = "Pablo Cardona Perez", email = "pablo.cardona_perez@ens-lyon.fr" }
]

dependencies = [
  "numpy>=1.22.0",
  "MDAnalysis>=2.1.0",
]

[project.optional-dependencies]
test = [
  "pytest>=6.2.5",
  "pytest-cov>=3.0.0",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["mixer*"]

[tool.setuptools.package-data]
shaker = ["data/**/*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=mixer --cov-report=term"
filterwarnings = [
    "ignore::DeprecationWarning:pkg_resources.*",
    "ignore::DeprecationWarning:scikits.*",
]