import subprocess
from pathlib import Path
from .parser import ITPTopology

'''
This should contain the fragment assembly workflow.
'''

def merge_itps(itps, redundancy_priority=None, 
               resname='MIX', outdir=".", author='Mixer'):
    """
    Merge multiple .itp fragments into a single topology using ITPTopology /
    GromacsITPParser.
    Parameters
    ----------
    itps : sequence of str or Path
        Input fragment .itp files, in merge order.
    resname : str
        Residue name to assign in the final topology.
    redundancy_priority : sequence of bool or None, optional
        For each fragment, whether it should override colliding entries from
        previously merged fragments. The first entry is always ignored (the
        first fragment is the base). If None, all subsequent fragments defer
        to the base (keep_second=False for all merges).
    outdir : str or Path, default "."
        Output directory.
    author : str, default "Mixer"
        Author name embedded in the file header.
    Returns
    -------
    Path
        Path to the merged output .itp.
    """
    
    if not itps:
        raise ValueError("No input .itp files were provided.")

    if redundancy_priority is None:
        redundancy_priority = [False] * len(itps)
    elif len(redundancy_priority) != len(itps):
        raise ValueError("redundancy_priority must have the same length as itps.")

    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    outpath = outdir / f"{resname}.itp"

    header = [f";;; Topology automatically generated by {author}.\n",
              ";;; Composed of the following fragment .itps:\n",]
    
    for itp in itps:
        header.append(f";;; {itp}\n")
    header.append("\n")

    mainparser = ITPTopology.from_file(itps[0])
    for idx, itp in enumerate(itps[1:], start=1):
        secondparser = ITPTopology.from_file(itp)
        mainparser.merge(secondparser, keep_second=redundancy_priority[idx])

    mainparser.set_resname(resname)
    mainparser.write_itp(outpath)

    original_text = outpath.read_text()  # Prepend header
    outpath.write_text("".join(header) + original_text)

    return outpath